# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

site_name: check_meinberg_lantime
site_description: A collection of monitoring plugins to check Meinberg Lantime devices with Icinga, Nagios and other compatible monitoring solutions.
site_url: https://dinotools.github.io/monitoring-check_meinberg_lantime/

repo_name: DinoTools/monitoring-check_meinberg_lantime
repo_url: https://github.com/DinoTools/monitoring-check_meinberg_lantime
edit_uri: blob/main/docs/

nav:
    - Home: index.md
    - License: LICENSE.md
    - Changelog: CHANGELOG.md
    - Issue Tracker: https://github.com/DinoTools/monitoring-check_meinberg_lantime/issues
    - Git Repo: https://github.com/DinoTools/monitoring-check_meinberg_lantime
    - ... | commands/*.md

docs_dir: docs

theme:
    name: material
    # Don't load external fonts
    font: false
    icon:
        repo: fontawesome/brands/github

markdown_extensions:
    - attr_list

plugins:
    - awesome-pages
    - search
